import React, { useState } from 'react';
import { Heart, ShieldCheck, HelpCircle, Mail, FileText, X } from 'lucide-react';

export default function Footer() {
  const [activeModal, setActiveModal] = useState(null); // 'about', 'contact', 'privacy', 'terms', 'help'

  const modalContent = {
    about: {
      title: 'About EduGen AI',
      body: 'EduGen AI is a purpose-built educational intelligence platform crafted specifically for school teachers handling Classes 1 to 10 across JKBOSE, CBSE, and State Boards. Our mission is to eliminate weekend exam-paper drafting burnout and empower educators with rigorous, curriculum-aligned assessment tools.'
    },
    contact: {
      title: 'Contact Teacher Support',
      body: 'Reach out to the EduGen AI Academic Team:\n\n• Email: support@edugen.school.edu\n• Helpline: +91 194 245-EDUGEN (9 AM – 6 PM IST)\n• Dedicated Teacher WhatsApp Community: +91 94190-EDUGEN'
    },
    privacy: {
      title: 'Teacher & Student Privacy Policy',
      body: 'EduGen AI strictly respects institutional privacy. All examination questions, student submissions, and answer sheets processed through the AI Paper Checker remain confidential. We do not sell, scrape, or share student data with third-party advertisers.'
    },
    terms: {
      title: 'Terms of Service',
      body: 'The question papers, marking schemes, and worksheets generated by EduGen AI are free for educational use in registered schools, tutorial centers, and home schooling. Teachers retain full rights to edit and customize any generated material.'
    },
    help: {
      title: 'Help & Knowledge Base',
      body: 'Quick Start Tips:\n\n1. Select your Board (JKBOSE / CBSE) and Class (1–10).\n2. Multi-select chapters using the quick tags.\n3. Click "Generate 100-Mark Paper" to produce all 7 mandated sections (MCQs, Blanks, T/F, VSA, Short, Long, HOTS).\n4. Click "Print / Export PDF" for instant A4 printing with zero browser margins.'
    }
  };

  return (
    <footer className="no-print" style={{
      marginTop: '60px',
      borderTop: '1px solid var(--border-light)',
      padding: '32px 0 20px',
      display: 'flex',
      flexDirection: 'column',
      gap: '16px'
    }}>
      {/* Links Bar */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '24px',
        flexWrap: 'wrap',
        fontSize: '0.86rem'
      }}>
        <button
          onClick={() => setActiveModal('about')}
          style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', fontWeight: '500' }}
        >
          About
        </button>
        <span style={{ color: 'var(--border-strong)' }}>•</span>

        <button
          onClick={() => setActiveModal('contact')}
          style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', fontWeight: '500' }}
        >
          Contact
        </button>
        <span style={{ color: 'var(--border-strong)' }}>•</span>

        <button
          onClick={() => setActiveModal('privacy')}
          style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', fontWeight: '500' }}
        >
          Privacy Policy
        </button>
        <span style={{ color: 'var(--border-strong)' }}>•</span>

        <button
          onClick={() => setActiveModal('terms')}
          style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', fontWeight: '500' }}
        >
          Terms
        </button>
        <span style={{ color: 'var(--border-strong)' }}>•</span>

        <button
          onClick={() => setActiveModal('help')}
          style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', fontWeight: '500' }}
        >
          Help & Docs
        </button>
      </div>

      {/* Bottom Love for Teachers line */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '6px',
        fontSize: '0.9rem',
        fontWeight: '600',
        color: 'var(--text-dark)'
      }}>
        <span>Made with</span>
        <Heart size={16} fill="#EF4444" color="#EF4444" />
        <span>for Teachers</span>
      </div>

      <div style={{ textAlign: 'center', fontSize: '0.76rem', color: 'var(--text-subtle)' }}>
        © {new Date().getFullYear()} EduGen AI. Designed for Classes 1–10 JKBOSE, CBSE & State Board Educators.
      </div>

      {/* Simple Information Modal */}
      {activeModal && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          background: 'rgba(15, 23, 42, 0.5)',
          backdropFilter: 'blur(4px)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 9999,
          padding: '20px'
        }}>
          <div className="card-glass" style={{
            maxWidth: '520px',
            width: '100%',
            padding: '28px',
            borderRadius: 'var(--radius-xl)',
            boxShadow: 'var(--shadow-modal)'
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <h3 style={{ fontSize: '1.2rem', fontWeight: '800', color: 'var(--text-dark)' }}>
                {modalContent[activeModal].title}
              </h3>
              <button
                onClick={() => setActiveModal(null)}
                style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)' }}
              >
                <X size={20} />
              </button>
            </div>

            <p style={{ fontSize: '0.92rem', color: 'var(--text-body)', lineHeight: 1.6, whiteSpace: 'pre-line', marginBottom: '24px' }}>
              {modalContent[activeModal].body}
            </p>

            <button
              onClick={() => setActiveModal(null)}
              className="btn-primary"
              style={{ width: '100%', padding: '10px' }}
            >
              Close
            </button>
          </div>
        </div>
      )}
    </footer>
  );
}
